<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ICU4N_version_warning_test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ICU4N" Version="60.1.0-alpha.449.g88112a7865" />
  </ItemGroup>

</Project>
